spring.datasource.url=jdbc:postgresql://localhost:5433/onepiece_db
spring.datasource.username=postgres
spring.datasource.password=Student_1234

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true